language: scala
jdk: oraclejdk8
scala:
- 2.11.12
sudo: false
script:
- ".ci/build.sh"
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
